osp/urls.py
from django.conf.urls import url

from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<prod_name>.+)/basket/$', views.add_to_basket, name='add_to_basket'),
    url(r'^basket/$', views.basket, name='basket'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^history/$', views.history, name='history'),
    url(r'^wishlist/$', views.wishlist, name='wishlist'),
    url(r'^(?P<prod_name>.+)/wishlist/$', views.add_to_wishlist, name='add_to_wishlist'),
    url(r'^additem/$', views.add_item, name='add_item'),
    url(r'^edititem/(?P<prod_name>.+)/$', views.edit_item, name='edit_item'),
    url(r'^delitem/(?P<prod_name>.+)/$', views.del_item, name='del_item'),
    url(r'^itemhistory/(?P<prod_name>.+)/$', views.item_history, name='item_history'),
    url(r'^(?P<prod_name>.+)/details/$', views.detail, name='detail'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/logged_out/'}),
    url(r'^logged_out/$', views.logged_out, name='logged_out'),
]

shop_portal/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'shop_portal.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'', include('osp.urls', namespace="osp")),
    url(r'^admin/', include(admin.site.urls)),
    url('^', include('django.contrib.auth.urls')),
)

osp/models.py
from django.db import models
from datetime import datetime

class Customer(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name


class Transaction(models.Model):
    customer = models.OneToOneField(Customer, null=True)


class Basket(models.Model):
    customer = models.ForeignKey(Customer, null=True)
    totalbill = models.IntegerField()
    transaction = models.ForeignKey(Transaction, null=True)
    current = models.BooleanField(default=True)
    date = models.DateTimeField(default=datetime.now, blank=True)


class Wishlist(models.Model):
    customer = models.OneToOneField(Customer, null=True)


class Item(models.Model):
    name = models.CharField(max_length=50)
    cost = models.IntegerField()
    discount = models.SmallIntegerField(default=0)
    available = models.IntegerField(default=1)
    purchase_quantity = models.IntegerField(default=0)
    listed = models.BooleanField(default=True)
    basket = models.ManyToManyField(Basket)
    wishlist = models.ManyToManyField(Wishlist)
    seller = models.CharField(max_length=50, null=True)

    def __unicode__(self):
        return self.name

osp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from osp.models import Item, Basket, Customer, Transaction, Wishlist
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.db import IntegrityError
from datetime import datetime
from django.contrib.auth.decorators import login_required


def userassert(req):
    if req.user.is_authenticated():
        if req.user.username == 'admin':
            return 'defaultguest'
        else:
            return req.user.username
    else:
        return 'defaultguest'


def index(request):
    if request.user.has_perm('osp.change_item'):
        item_list = Item.objects.filter(listed=True, seller=request.user.username)
    else:
        item_list = Item.objects.filter(listed=True)
    context = {'item_list': item_list}
    return render(request, 'osp/index.html',context)


def basket(request):
    current_user = userassert(request)
    try:
        basket = Basket.objects.get(current=True, customer__name=current_user)
    except ObjectDoesNotExist:
        try:
            c = Customer.objects.get(name=current_user)
        except ObjectDoesNotExist:
            c = Customer(name=current_user)
            c.save()
        basket = Basket(customer=c, totalbill=0, current=True)
        basket.save()
    context = {'basket': basket}
    return render(request, 'osp/basket.html', context)


def detail(request, prod_name):
    item = Item.objects.get(name=prod_name, listed=True)
    if request.user.has_perm('osp.change_item') and item.seller == request.user.username:
        edit = True
    else:
        edit = False

    context = {'item': item,
               'edit': edit }
    return render(request, 'osp/detail.html', context)


def add_to_basket(request, prod_name):
    current_user = userassert(request)

    try:
        c = Customer.objects.get(name=current_user)
    except ObjectDoesNotExist:
        c = Customer(name=current_user)
        c.save()

    try:
        basket = Basket.objects.get(current=True, customer=c)
    except ObjectDoesNotExist:
        basket = Basket(customer=c, totalbill=0, current=True)
        basket.save()

    try:
        item = basket.item_set.get(name=prod_name)
    except ObjectDoesNotExist:
        item = Item.objects.get(name=prod_name, listed=True)
        # Create an unlisted copy of item
        item.pk = None
        item.id = None
        item.wishlist_id = None
        item.listed = False
        item.save()
        basket.item_set.add(item)    

    item.purchase_quantity += int(request.POST['numofitems'])
    dis = (item.discount/100) * item.cost
    t = (item.purchase_quantity * item.cost) - dis
    item.save()
    basket.totalbill += t
    basket.save()

    return HttpResponseRedirect(reverse('osp:basket'))


def add_to_wishlist(request, prod_name):
    current_user = userassert(request)
    item = Item.objects.get(name=prod_name, listed=True)
    try:
        c = Customer.objects.get(name=current_user)
    except:
        c = Customer(name=current_user)
        c.save()

    try:
        wishlist = Wishlist.objects.get(customer__name=current_user)
    except ObjectDoesNotExist:
        wishlist = Wishlist(customer=c)
        wishlist.save()
    wishlist.item_set.add(item)
    return HttpResponseRedirect(reverse('osp:wishlist'))


def wishlist(request):
    current_user = userassert(request)
    try:
        wishlist = Wishlist.objects.get(customer__name=current_user)
    except ObjectDoesNotExist:
        try:
            c = Customer.objects.get(name=current_user)
        except ObjectDoesNotExist:
            c = Customer(name=current_user)
            c.save()
        wishlist = Wishlist(customer=c)
        wishlist.save()
    context = {'wishlist': wishlist}
    return render(request, 'osp/wishlist.html', context)


def checkout(request):
    current_user = userassert(request)
    basket = Basket.objects.get(current=True, customer__name=current_user)
    c = Customer.objects.get(name=current_user)
    
    try:
        transaction = Transaction(customer=c)
        transaction.save()
    except IntegrityError:
        transaction = Transaction.objects.get(customer__name=current_user)
        transaction.basket_set.add(basket)
    
    try:
        basket = Basket.objects.get(current=True, customer=c)
        basket.date = datetime.now()
        basket.current = False
        basket.save()
        transaction.basket_set.add(basket)
    except ObjectDoesNotExist:
        pass

    return render(request, 'osp/checkout.html', )


def history(request):
    current_user = userassert(request)
    try:
        transaction = Transaction.objects.get(customer__name=current_user)
    except ObjectDoesNotExist:
        transaction = Transaction(customer=None)  
        pass
    return render(request, 'osp/history.html', {'t': transaction})


def add_item(request):
    current_user = userassert(request)
    if request.method == 'POST':
        n = request.POST['itemname']
        c = int(request.POST['cost'])
        d = int(request.POST['discount'])
        a = int(request.POST['available'])
        newitem = Item(name=n, cost=c, discount=d, available=a, seller=current_user)
        newitem.save()
        return render(request, 'osp/itemadded.html',) 
    else:
        return render(request, 'osp/additem.html',)


def edit_item(request, prod_name):
    item = Item.objects.get(name=prod_name, listed=True)
    if request.user.has_perm('osp.change_item') and item.seller == request.user.username:
        edit = True
    else:
        edit = False

    context = {'item': item,
               'edit': edit }

    if request.method == 'POST':
        item.name = request.POST['itemname']
        item.cost = int(request.POST['cost'])
        item.discount = int(request.POST['discount'])
        item.available = int(request.POST['available'])
        item.save()
        return HttpResponseRedirect(reverse( 'osp:detail', args=(item.name,)))
    else:
        return render(request, 'osp/edititem.html', context)


def del_item(request, prod_name):
    item = Item.objects.get(name=prod_name, listed=True)
    if request.user.has_perm('osp.delete_item') and item.seller == request.user.username:
        item.delete()

    return HttpResponseRedirect(reverse('osp:index'))


def item_history(request, prod_name):
    seller_item_basket = Basket.objects.filter(item__name=prod_name)
    return render(request, 'osp/itemhistory.html', 
                  {'seller_item_basket': seller_item_basket,
                   'item'              : prod_name })


def logged_out(request):
    """
    Custom view to render logged out template 
    as the default logout view would not render it

    """
    return render(request, 'osp/logged_out.html',)

osp/templates/osp/additem.html
{% extends "osp/base.html" %}

{% block content %}
<script>
    $('#additem').addClass('active');
</script>

{% if perms.osp.add_item %}
<h3>Add new item</h3>

<form role="form" action="{% url 'osp:add_item' %}" method="post">
{% csrf_token %}
<div class="form-group">
    <label for="name">Item name:</label>
    <input type="text" class="form-control" name="itemname">
</div>
<div class="form-group">
    <label for="number">Price:</label>
    <input type="number" class="form-control" name="cost">
</div>
<div class="form-group">
    <label for="number">Discount:</label>
    <input type="number" class="form-control" name="discount">
</div>
<div class="form-group">
    <label for="number">Number of items to add (availability):</label>
    <input type="number" class="form-control" name="available">
</div>
<input type="submit" class="btn btn-default" value="Add item">
</form>
{% else %}
<h3>You can't add items.</h3>
{% endif %}

{% endblock %}

osp/templates/osp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Online shopping portal</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
                <a class="navbar-brand" href="#">Onlineshopport</a>
        </div>
        <div>
            <ul class="nav navbar-nav">
                <li id="home"><a href="{% url 'osp:index' %}">Home</a></li>
                {% if not perms.osp.add_item %}
                    <li id="basket"><a href="{% url 'osp:basket' %}">Basket</a></li>
                    <li id="history"><a href="{% url 'osp:history' %}">History</a></li>
                    <li id="wishlist"><a href="{% url 'osp:wishlist' %}">Wishlist</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a>Welcome,
                {% if user.is_anonymous %}
                <em> Guest! </em></a>
                </li>
                <li id='login'><a href="{% url 'login' %}">Login <span class="glyphicon glyphicon-log-in"></span></a></li>
                {% else %}
                <em> {{ user }}! </em></a></li>
                <li><a href="{% url 'logout' %}">Logout <span class="glyphicon glyphicon-log-out"></span></a></li>
                {% endif %}
                {% if perms.osp.add_item %}
                <li id='additem'><a href="{% url 'osp:add_item' %}">+Item</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <p>
    {% block content %}

    {% endblock %}
    </p>
</div>
</body>
</html>

osp/templates/osp/basket.html
{% extends "osp/base.html" %}

{% block content %}
<script>
    $('#basket').addClass('active');
</script>

<h3>Shopping basket</h3>
{% if not basket.item_set.all %}
    <p>No items.</p>
{% else %}
    <ol>
    {% for item in basket.item_set.all %}
        <li><a href="{% url 'osp:detail' item.name %}">{{ item.name }}</a> - Rs {{ item.cost }} - Quantity: {{ item.purchase_quantity }}</li>
    {% endfor %}
    </ol>
    Total: {{ basket.totalbill }}
    <br />
    <a href="{% url 'osp:checkout' %}">Checkout</a>
{% endif %}

{% endblock %}

osp/templates/osp/checkout.html
{% extends "osp/base.html" %}

{% block content %}
<h3>You have checked out!</h3>
<br>
<h2><a href="{% url 'osp:history' %}">Order history</a></h2>
{% endblock %}

osp/templates/osp/detail.html
{% extends "osp/base.html" %}

{% block content %}

<h3>{{ item.name }}</h3> 

Price: Rs {{ item.cost }}
<br>
Discount: {{ item.discount }}
<br>
Seller: {{ item.seller }}
<br>
Available: {{ item.available }}

{% if not edit %}
<form action="{% url 'osp:add_to_basket' item.name %}" method="post">
{% csrf_token %}
Items to add: <input type="number" name="numofitems" id="numofitems" value="1"/>
<br>
<br>
<input type="submit" class="btn btn-primary" value="Add to basket" />
</form>

<form action="{% url 'osp:add_to_wishlist' item.name %}" method="post">
{% csrf_token %}
<input type="submit" class="btn btn-default" value="Add to wishlist" />
</form>
{% endif %}
{% if edit %}
    <br><br>
    <div class="btn-group">
    <a href="{% url 'osp:edit_item' item.name %}" class="btn btn-primary">Edit</a>
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#confirm">Delete</button>
    <!-- <a href="{# url 'osp:del_item' item.name #}" class="btn btn-danger">Delete</a> -->
    <a href="{% url 'osp:item_history' item.name %}"class="btn btn-primary">Purchase history</a>
    </div>

<div id="confirm" class="modal fade" role="dialog">
    <div class="modal-dialog">

    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Confirmation</h4>
        </div>
        <div class="modal-body">
            <p>Are you sure you want to delete {{ item.name }}?</p>
        </div>
        <div class="modal-footer">
            <a href="{% url 'osp:del_item' item.name %}" class="btn btn-danger">Delete</a>
        </div>
    </div>
    </div>
</div>

{% endif %}

{% endblock %}

osp/templates/osp/edititem.html
{% extends "osp/base.html" %}

{% block content %}

<h3>Edit item {{ item.name }}</h3>

{% if edit %}
<form action="{% url 'osp:edit_item' item.name %}" method="post">
{% csrf_token %}
New item name:<br>
<input type="text" name="itemname" value="{{ item.name }}"/>
<br>
New price:<br>
<input type="number" name="cost" value="{{ item.cost }}"/>
<br>
New discount:<br>
<input type="number" name="discount" value="{{ item.discount }}"/>
<br>
New number of items to add (availability):<br>
<input type="number" name="available" value="{{ item.available }}"/>
<br>
<br>
<input type="submit" class="btn btn-default" value="Save changes" />
</form>
{% else %}
You don't have the permission to edit this item.
{% endif %}

{% endblock %}

osp/templates/osp/history.html
{% extends "osp/base.html" %}

{% block content %}
<script>
    $('#history').addClass('active');
</script>

<h3>Order History</h3>

{% if not t.basket_set.all %}
    <p>No past orders.</p>
{% else %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Date</th>
                <th>Items</th>
                <th>Total</th>
            </tr>
        </thead>
    <tbody>
        {% for basket in t.basket_set.all %}
        <tr>
        <td>{{ basket.date }}</td>
        <td>
        <ul>
        {% for item in basket.item_set.all %}
        <li>{{ item.name }} - {{ item.cost }} - Qty: {{ item.purchase_quantity }}</li>
        {% endfor %}
        </ul>
        </td>

        <td>{{ basket.totalbill }}</td> 
        </tr>
        {% endfor %}
    </tbody>
    </table>
{% endif %}

{% endblock %}

osp/templates/osp/index.html
{% extends "osp/base.html" %}

{% block content %}
<script>
$(document).ready(function(){
    $('#home').addClass('active');
});
</script>

<h1>Shop online!</h1>
{% if perms.osp.add_item %}
    <h3>Your items</h3>
{% else %}
    <h3>Available items</h3>
{% endif %}
{% if item_list %}
    <ul>
    {% for item in item_list %}
    <li><a href="{% url 'osp:detail' item.name %}">{{ item.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Stock empty.</p>
{% endif %}

{% endblock %}

osp/templates/osp/itemadded.html
{% extends "osp/base.html" %}

{% block content %}
<h3>New item added!</h3>
{% endblock %}

osp/templates/osp/itemhistory.html
{% extends "osp/base.html" %}

{% block content %}

<h3>Purchase history for {{ item }}</h3>
<ol>
{% for b in seller_item_basket %}
    <li>
    {{ b.customer.name }} <br>
    {{ b.date }} <br>
    </li>
    <br>
{% endfor %}
</ol>

{% endblock %}

osp/templates/osp/logged_out.html
{% extends "osp/base.html" %}
{% block content %}
<h4>Logged out!</h4>
{% endblock %}

osp/templates/osp/wishlist.html
{% extends "osp/base.html" %}

{% block content %}
<script>
    $('#wishlist').addClass('active');
</script>

<h3>Wishlist</h3>
{% if not wishlist.item_set.all %}
    <p>No items in your wishlist.</p>
{% else %}
    <ol>
    {% for item in wishlist.item_set.all %}
        <li><a href="{% url 'osp:detail' item.name %}">{{ item.name }}</a> - Rs{{ item.cost }}
        <br>
        <form action="{% url 'osp:add_to_basket' item.name %}" method="post">
{% csrf_token %}
        Qty: <input type="number" class="form-control" name="numofitems" id="numofitems" value="1"/>
        <input type="submit" class="btn btn-default" value="Move to basket" />
        </form>
        </li>
        <br>
    {% endfor %}
{% endif %}

{% endblock %}